### ISSUE TITLE
代码只关注于charge  prediction  任务吗

### ISSUE THREAD

**Issue by hecongqing** [srhthu/LM-CompEval-Legal#3]

**Comment by srhthu** [comment]
您好，是的，这个benchmark只采用了judgment prediction中的charge prediction这个子任务。另外一个子任务，penalty prediction，由于难度比较大，需要更多专业知识，所以没有放在benchmark里面。

Hi, our benchamrk only includes the charge prediction task, which is one of the sub-tasks of judgment prediction. The other sub-task, namely penalty prediction, is not included as it is challenging and requires more domain knowledge and expertise reasoning.

**Comment by hecongqing** [comment]
好的谢谢
